#!/usr/bin/env python3
"""Generate PNG and Android vectors from the path-only SVG. Requires rsvg-convert."""
from pathlib import Path
import subprocess
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parents[1]
source = root / 'docs/assets/butler.svg'
svg = ET.parse(source).getroot()
paths = list(svg.findall('{http://www.w3.org/2000/svg}path'))
res = root / 'app/src/main/res'

def vector(name, launcher=False):
    viewport = 108 if launcher else 512
    lines = ['<!-- Generated by scripts/render-brand.py; edit docs/assets/butler.svg. -->',
             f'<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{viewport}dp" android:height="{viewport}dp" android:viewportWidth="{viewport}" android:viewportHeight="{viewport}">']
    if launcher:
        # Center the artwork, not the SVG canvas. Width 56dp in the 72dp masked
        # viewport; all artwork stays inside the central 66dp safe circle.
        lines.append('  <group android:scaleX="0.25" android:scaleY="0.25" android:translateX="-10" android:translateY="-11">')
    for p in paths:
        lines.append(f'  <path android:fillColor="{p.attrib["fill"]}" android:pathData="{p.attrib["d"]}"/>')
    if launcher:
        lines.append('  </group>')
    lines.append('</vector>')
    (res / f'drawable/{name}.xml').write_text('\n'.join(lines) + '\n')

vector('butler_character')
vector('ic_launcher_foreground', launcher=True)
for qualifier, themed in [('mipmap-anydpi-v26', False), ('mipmap-anydpi-v33', True)]:
    folder = res / qualifier
    folder.mkdir(exist_ok=True)
    lines = ['<!-- Generated by scripts/render-brand.py. -->',
             '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">',
             '  <background android:drawable="@color/ic_launcher_background"/>',
             '  <foreground android:drawable="@drawable/ic_launcher_foreground"/>']
    if themed:
        lines.append('  <monochrome android:drawable="@drawable/ic_launcher_foreground"/>')
    lines.append('</adaptive-icon>')
    (folder / 'ic_launcher.xml').write_text('\n'.join(lines) + '\n')
subprocess.run(['rsvg-convert', '-w', '1024', '-h', '1024', str(source), '-o', str(root / 'docs/assets/butler.png')], check=True)
